//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvanimal_Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int Id { get; set; }
        public int Especie { get; set; }
        public string Raca { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Observacoes { get; set; }
        public string Imagem { get; set; }
    
        public virtual Especies Especies { get; set; }
    }
}
